### ISSUE TITLE
Include minified browser build of json-webtoken

### ISSUE THREAD

**Issue by nichtich** [gbv/login-client#1]
[login-server api demo](https://github.com/gbv/login-server/blob/master/views/api.ejs) loads [json-webtoken](https://github.com/auth0/node-jsonwebtoken) from a custom build because browser builds [are not provided officially](https://github.com/auth0/node-jsonwebtoken/issues/405). The build (with `jwt.verify`, that's all we need) should better be included in the login-client repository as optional file to use when a client wants to verify tokens.

**Comment by stefandesu** [comment]
As long as it's a separate and optional file, it's fine. The browser build for jsonwebtoken is about 300 to 500 KB which is pretty massive considering what it does. 

Should we add it as a git submodule and add a separate script to package.json that refreshes and builds it?

**Comment by nichtich** [comment]
What's the benefit of client side validation of web token anyway? We could fully remove it from the client example if it's only relevant to server applications.
-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
We don't need client side validation, but because it's a demo, I thought it would be nice to showcase validation as well. 

I guess we could just do the same only without validation and add the piece of validation code to login-server's README.
