### ISSUE TITLE
Document typical pitfalls

### ISSUE THREAD

**Issue by nichtich** [gbv/login-client#10]
Typical errors:

> No 'Access-Control-Allow-Origin' header is present on the requested resource

The login server needs to allow your base URL as trusted Origin. Can be configured with `ALLOWED_ORIGINS` at jskos-server

> Connection is not possible because third-party cookies are blocked

Login server runs at a different domain so cookies are not sent. *What to do about it?*

**Comment by stefandesu** [comment]
Good points. It shouldn't have anything to do with jskos-server though because login-client only interacts with login-server. The generated JWTs are then used for authentication at jskos-server, but that's part of cocoda-sdk.
