### ISSUE TITLE
Add method to detect third-party connection problem

### ISSUE THREAD

**Issue by nichtich** [gbv/login-client#16]
As discussed at https://github.com/gbv/login-server/issues/90 login-server does not work with client applications on another domain if third-party cookies have been disabled - and this is the default on Firefox. Login-Client should provide a way to detect whether connection to login-server is not possible because third-party cookies are blocked. A heuristic may be based on timeout and detection of browser. Client applications may then show a message to explicitly allow third-party cookie. The method should at least distinguish between 

- login-server down or not reachable => no login possible,
- login-server running but login not possible likely because of blocked third party cookies => user can change its settings

With documentation this would also solve #10.

**Comment by stefandesu** [comment]
This is already implemented and it will return a ThirdPartyCookiesBlockedError. However, before closing this, I will check if it actually works as expected.

**Comment by nichtich** [comment]
Done and documented.
